/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javaDemo_jni_staticDemo_HelloWorld */

#ifndef _Included_javaDemo_jni_staticDemo_HelloWorld
#define _Included_javaDemo_jni_staticDemo_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javaDemo_jni_staticDemo_HelloWorld
 * Method:    getFromNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javaDemo_jni_staticDemo_HelloWorld_getFromNative
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
